# Generated by Django 5.2.4 on 2025-07-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airbnb_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_market', to='punch.market')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_role', to='punch.role')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_skill', to='punch.skill')),
            ],
        ),
    ]
